### ISSUE TITLE
yor-tag.sh Applying Tags to Resources without Tags Argument. 

### ISSUE THREAD

**Issue by luke-taylor** [Azure/tfmod-scaffold#13]
Hello, 

After running the `post-push` workflow, there exists a step which adds the `yor tags` to the resources. However, in my case these tags are getting applied to `azurerm_log_analytics_linked_service` which doesn't have any `tags` argument in general thus the following `terraform validate` step fails. 

I am not sure how to get around this.

**Comment by lonegunmanb** [comment]
Thanks @luke-taylor for reporting this issue to us, we'll take a look. Would you please tell me your AzureRM Provider's version? Thanks!

**Comment by lonegunmanb** [comment]
You're welcome @luke-taylor, it's me who owe you a thanks.

I've removed all azurerm resources that don't contain tags anymore from my special personal fork of `yor`, the latest runner image's version should be `v0.27.1`. The CI pipeline is building the image, please wait for 1-2 hours and then remove the wrong tags and kick off your pipeline again.

**Comment by luke-taylor** [comment]
The CI Pipeline now works! Feel free to close this issue, happy to have this one solved so quickly!

**Comment by lonegunmanb** [comment]
> The CI Pipeline now works! Feel free to close this issue, happy to have this one solved so quickly!

Thanks for the update @luke-taylor, I'm working with `yor` team to solve this issue once and for all.
