### ISSUE TITLE
make: *** No rule to make target 'fmtcheck'.  Stop.

### ISSUE THREAD

**Issue by LaurentLesle** [Azure/tfmod-scaffold#29]
When submitting a PR on a template repo https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine/actions/runs/7778845571/job/21209097854 I am getting the following error.

```bash
make: *** No rule to make target 'fmtcheck'.  Stop.
```

I can reproduce from codespace
https://github.com/Azure/terraform-azurerm-avm-template/blob/main/.github/actions/docs-check/action.yml

```bash
/workspaces/terraform-azurerm-avm-res-compute-virtualmachine (fix.linter) $ docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform make fmtcheck
Unable to find image 'mcr.microsoft.com/azterraform:latest' locally
latest: Pulling from azterraform
f6b24043e6a2: Pull complete 
cfe1aeec28bd: Pull complete 
c0b2cb60cb0a: Pull complete 
04704b2626a4: Pull complete 
e2ee94e2662d: Pull complete 
d6fe50ed6ba9: Pull complete 
6f7b86a314e3: Pull complete 
Digest: sha256:db74d53208e85768eaeba655375268f714acd4f9cd8b39fe1d3026c723d7fffd
Status: Downloaded newer image for mcr.microsoft.com/azterraform:latest
make: *** No rule to make target 'fmtcheck'.  Stop.
```

If I just run:
```bash
 docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform make
==> Generating module documentation...
terraform-docs -c .terraform-docs.yml .
README.md updated successfully
==> Generating examples documentation...
cd examples && for d in $(ls -d */); do terraform-docs  $d; done
basic_ubuntu_w_ssh_auth/README.md updated successfully
basic_windows_w_additional_disks_public_ip/README.md updated successfully
basic_windows_w_azure_monitor_agent/README.md updated successfully
basic_windows_w_encryption_at_host/README.md updated successfully
basic_windows_w_managed_identities_and_rbac/README.md updated successfully
```

So looks like my local code is correct but the attached job is failing.

**Comment by lonegunmanb** [comment]
Hi @LaurentLesle thanks for reporting this issue to us, I've checked your repo and your `Makefile` is obsolete.

No worries, you can just merge this [pr](https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine/pull/23), then try to run `./avm pr-check`, fix all issues it founds, then submit another pr.

**Comment by lonegunmanb** [comment]
I'm closing this issue since I assume the merge of [#23](https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachine/pull/23) has fixed this issue, please feel free to reopen it if it's not @LaurentLesle .
