### ISSUE TITLE
fumptcheck script fails to update go tests

### ISSUE THREAD

**Issue by kevball2** [Azure/tfmod-scaffold#34]
The current `fumptcheck` checks for go tests and will stop the `pr-check` if any are found. 
`make fumpt` does not successfully update go tests erroring: 
 
curl -H 'Cache-Control: no-cache, no-store' -sSL ""https://raw.githubusercontent.com/Azure/tfmod-scaffold/main/avm_scripts"/go-fumpt.sh" | bash
==> Fixing source code with Gofumpt...
make: *** [avmmakefile:18: fumpt] Error 1

I tried to update and test the scripts locally but was unable to get the scripts to run in a local container or in WSL. 

Module I am testing with - https://github.com/kevball2/terraform-azurerm-avm-res-resource-resourcegroup

**Comment by lonegunmanb** [comment]
Thanks @kevball2 for reporting this issue to us, I think we've fixed the script, would you please try again?

Btw, I've reviewed your repo, unlike in TFVM, in AVM you won't be required to write go-implemented e2e tests for examples, you can remove all sub folders in your `tests` folder, unless you'd like to add some unit tests there. The AVM core team decided to use new `terraform test` feature as AVM's main testing framework.

**Comment by kevball2** [comment]
@lonegunmanb,  Tested the script and it is working corretly now. 
Thanks for the info testing, I was going off the current style guide listing - https://azure.github.io/Azure-Verified-Modules/specs/terraform/#id-tfnfr5---category-testing---test-tooling 
I'll ask over in the AVM repo if they have examples around  `terraform test` 
I have some validation tests already created but would like to get some example deployments created as well as a reference.
