### ISSUE TITLE
tflint does not catch unused variables

### ISSUE THREAD

**Issue by zioproto** [Azure/tfmod-scaffold#40]
I recently noticed that the tflint configuration does not catch unused variables.

Example:
https://github.com/Azure/terraform-azurerm-avm-ptn-aks-production/pull/59/files

The root cause seems to be `terraform_unused_declarations` disabled in the configuration:

https://github.com/Azure/tfmod-scaffold/blob/1949cd5a69cd3424fc84312995bb60ddc62542a7/avm.tflint.hcl#L90-L93

**Comment by matt-FFFFFF** [comment]
This is fixed now thanks to #39
