### ISSUE TITLE
terraform-docs output formet

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/tfmod-scaffold#8]
Meeting with @grayzu and have raised an issue here

https://github.com/Azure/tfmod-scaffold/blob/4c0e5224a6091aec231f2c9623d310c7a1091bd6/GNUmakefile#L80

Forcing the use of the table format prevents use of Heredoc format for more complex variable inputs.

https://github.com/Azure/terraform-azurerm-lz-vending/blob/main/variables.virtualnetwork.tf

Consider the above file, the virtual_networks input is complex, and I use embedded Markdown to describe the fields in the map. As this is formatted as using the `markdown document` rather than `markdown table` this embedded Markdown is correctly rendered.

Perhaps we should mandate that a .tfdocs-config file is used and that the formatter is either `markdown document` or `markdown table`??

https://github.com/Azure/terraform-azurerm-lz-vending/blob/main/.tfdocs-config.yml

/cc @jtracey93

**Comment by lonegunmanb** [comment]
Brilliant idea! I would see what I can do. Thanks @matt-FFFFFF !

**Comment by lonegunmanb** [comment]
Hi @matt-FFFFFF, I've added support for customized terraform-docs config file, now you can use a `.terraform-docs.yml` file. Would you please give it a try? Thanks.

**Comment by matt-FFFFFF** [comment]
Looks great - I will test it shortly, thanks!
